# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hydra

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - git checkout -- go.sum

builds:
  -
    id: hydra
    ldflags:
      - -s -w -X github.com/ory/hydra/driver/config.Version={{.Tag}} -X github.com/ory/hydra/driver/config.Commit={{.FullCommit}} -X github.com/ory/hydra/driver/config.Date={{.Date}}
    binary: hydra
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux

archives:
  - id: hydra
    builds:
      - hydra
    replacements:
      amd64: 64bit
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - ci skip
      - Merge pull request
      - Merge branch

checksum:
  algorithm: sha256


release:
  prerelease: auto
  name_template: "{{.Tag}}"
  ids:
    - hydra
