# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hydra

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go install github.com/gobuffalo/packr/v2/packr2
    - packr2

builds:
  -
    id: hydra
    ldflags:
      - -s -w -X github.com/ory/hydra/cmd.Version={{.Tag}} -X github.com/ory/hydra/cmd.Commit={{.FullCommit}} -X github.com/ory/hydra/cmd.Date={{.Date}}
    binary: hydra
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      # See https://github.com/DataDog/dd-trace-go/issues/753
      # See https://github.com/DataDog/dd-trace-go/pull/754
      # - freebsd
      - linux

archives:
  - builds:
      - hydra
    id: hydra-archive
    replacements:
      amd64: 64-bit

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc


release:
  prerelease: auto
