# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hydra

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - git checkout -- go.sum

builds:
  -
    id: hydra
    ldflags:
      - -s -w -X github.com/ory/hydra/driver/config.Version={{.Tag}} -X github.com/ory/hydra/driver/config.Commit={{.FullCommit}} -X github.com/ory/hydra/driver/config.Date={{.Date}}
    binary: hydra
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux

archives:
  - id: hydra-sqlite
    builds:
      - hydra-sqlite-windows
      - hydra-sqlite-darwin
      - hydra-sqlite-linux
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md
    name_template: "{{ .ProjectName }}_{{ .Version }}-sqlite_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: hydra-sqlite-libmusl
    builds:
      - hydra-sqlite-linux-libmusl
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md
    name_template: "{{ .ProjectName }}_{{ .Version }}-sqlite-libmusl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: hydra
    builds:
      - hydra
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - ci skip
      - Merge pull request
      - Merge branch

brews:
  - tap:
      owner: ory
      name: homebrew-hydra
    ids:
      - hydra-sqlite
    homepage:  https://www.ory.sh
    commit_author:
      name: aeneasr
      email: 3372410+aeneasr@users.noreply.github.com
    install: |
      bin.install "hydra"

scoop:
  bucket:
    owner: ory
    name: scoop-hydra
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: 3372410+aeneasr@users.noreply.github.com

checksum:
  algorithm: sha256


release:
  prerelease: auto
  name_template: "{{.Tag}}"
  ids:
    - hydra
